FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY {{ path }}/Build/ ./Build/
COPY {{ path }}/index.html ./index.html
COPY {{ path }}/nginx.conf /etc/nginx/conf.d/default.conf

RUN chown -R nginx:nginx /usr/share/nginx/html \
    && chmod -R a+rX /usr/share/nginx/html
